/**
 * ESLint flat config.
 *
 * `next lint` was removed in Next.js 16 — the CLI has no `lint` command at all,
 * so `npm run lint` was reading "lint" as a directory argument and failing.
 * Linting now runs through the ESLint CLI directly, per
 * node_modules/next/dist/docs/01-app/03-api-reference/05-config/03-eslint.md.
 *
 * Note that `next build` no longer runs the linter either, so CI has to invoke
 * this itself rather than assuming a build covers it.
 */
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTypeScript,
  {
    /*
     * eslint-config-next bundles an eslint-plugin-react old enough that its
     * React-version *detection* crashes on ESLint 10 (it calls
     * `context.getFilename()`, removed in this major). Stating the version
     * outright skips detection entirely, which is both a fix and more honest
     * than sniffing the tree for a version we already pin in package.json.
     */
    settings: { react: { version: "19.2" } },
  },
  globalIgnores([
    // Defaults from eslint-config-next, which are replaced rather than merged.
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by drizzle-kit; not ours to lint.
    "drizzle/**",
    // The original prototype, kept verbatim as reference. It is documentation
    // of where this came from, not code we ship or intend to fix.
    "docs/**",
  ]),
]);
